# Generated by Django 4.2.11 on 2024-04-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0002_book_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
    ]
