# Generated by Django 5.0.4 on 2024-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False),
        ),
    ]
